

# PIR / ds1820 sensor
pir:
	./sendlua.py -r lua/tx.lua 3rdparty/ds1820.lua lua/pir.lua lua/pir_temp.lua -w init.lua
	./sendlua.py -r 

# Grove Dust sensor : requires dust module building into Lua binary
dust:
	./sendlua.py -r lua/tx.lua lua/grove_dust.lua -w init.lua
	./sendlua.py -r 

